server:
  #端口号
  port: 8061

spring:
  profiles:
    active: dev
  application:
    name: points
  jackson:
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.kunyiduan.entity
  default-executor-type: REUSE
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-underline: true
      id-type: ID_WORKER_STR
      db-type: mysql
  instance:
    preferIpAddress: true
