server:
  port: 8081

spring:
  application:
    name: direct-provider
  jackson:
    time-zone: GMT+8
  rabbitmq:
    host: 10.13.3.120
    port: 45672
    username: kunyiduan
    password: 123456
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5

mq:
  config:
    exchange: time.direct

logging:
  level:
    root: info