server:
  port: 8761                    # ???Eureka?????

spring:
  security:
    basic:
      enabled: true
    user:
      name: root
      password: 123456

eureka:
  instance:
    hostname: 127.0.0.1         # ???Eureka??????
  client:
    registerWithEureka: false    #?????Eureka Server?????true
    fetchRegistry: false   #???Eureka Server?????????????false??????????true
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/  #?????????????????
  server:
    enable-self-preservation: true   #?????eureka?????????
