spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost/user?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: '123456'
  redis:
    host: localhost
    port: 6379
    database: 1
    timeout: 2000
    password: 123456
  security:
    basic:
      enabled: true
    user:
      name: root
      password: 123456

swagger:
  enabled: true
  basic:
    username: root
    password: 123456

logging:
  level:
    root: info

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123456@localhost:8761/eureka/
  instance:
    preferIpAddress: true

mybatis-plus:
  configuration:
    # 打印执行的sql，开发或测试环境使用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

encryption:
  aes:
    secret: NyBGPAI)E*BDHw+BLSDA9PuekPiGFSU&
    slat: b6db1d1ec27811ea
  slat: oEjV0Y&aihJ~kkj&EQ~GPRT42^~BvYcx

token:
  expired: 1296000000 # 15*24*60*60*1000
  secret: Uk8eVNmrOmJjt8IIRz5Y4xOlYspP4Lp1


