server:
  port: 8084

spring:
  application:
    name: topic-consumer
  jackson:
    time-zone: GMT+8
  rabbitmq:
    host: 10.13.3.120
    port: 45672
    username: kunyiduan
    password: 123456
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5

mq:
  config:
    exchange: number.topic
    queue:
      odd: number.odd
      even: number.even

logging:
  level:
    root: info
