server:
  port: 8083

spring:
  application:
    name: fanout-provider
  jackson:
    time-zone: GMT+8
  rabbitmq:
    host: 10.13.3.120
    port: 5672
    username: kunyiduan
    password: 123456
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5

mq:
  config:
    exchange: number.fanout

logging:
  level:
    root: info
